### ISSUE TITLE
🐛[BUG]: Pytest getting killed on SFNO package test with wheel install

### ISSUE THREAD

**Issue by NickGeneva** [NVIDIA/earth2studio#68]
### Version

main

### On which installation method(s) does this occur?

Pip

### Describe the issue

Getting the classic uninformative:

`test/models/px/test_sfno.py::test_sfno_package[cpu] make: *** [Makefile:40: pytest] Killed`

Likely a memory issue. Some research suggests pytest can cause memory usage to compound between tests... 
One potential solution is to change the models loaded to a fixture to load the models [scoped to something](https://docs.pytest.org/en/6.2.x/fixture.html#fixture-scopes), seems tricky problem with these large models.

**Comment by NickGeneva** [comment]
Fixed by adding explicit memory request in helm chart of test container:

```
resources:
  requests:
      nvidia.com/gpu: 1
      memory: "64Gi"
  limits:
      nvidia.com/gpu: 1
      memory: "64Gi"
  ```
